wechat:
  appid:"wx1309577b6931b6cf"
  secret:"1f6b01eaf73c72e2da1d6f578f6f8b01"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wxapp?serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
#      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 600000
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
#      connection-init-sql: SET NAMES utf8mb4
server:
  port: 8088

mybatis:
  configuration:
    map-underscore-to-camel-case: true